export enum Options {

  LOG_LEVEL = "LOG_LEVEL",
  SERVER_PORT = "SERVER_PORT",
  GCP_SERVICE_ACCOUNT = "GCP_SERVICE_ACCOUNT",
  GCP_PUBSUB_SUBSCRIPTION = "GCP_PUBSUB_SUBSCRIPTION",
  FALCO_URL = "FALCO_URL"

}
